<a href="https://colab.research.google.com/github/HelloPenguin1/Spinal_Metastasis_Classification_TCIA/blob/main/Model_Train_I3DCNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import numpy
import sklearn
import torch

print(numpy.__version__)
print(sklearn.__version__)
print(torch.__version__)

2.0.2
1.6.1
2.11.0+cu128

In [2]:
!pip install -q monai SimpleITK nibabel

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 31.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 MB 24.0 MB/s eta 0:00:00

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

import tensorflow as tf
from tensorflow.keras import layers, models

from sklearn.model_selection import StratifiedGroupKFold
from sklearn.utils.class_weight import compute_class_weight

from monai.transforms import (
    Compose,
    RandFlip,
    RandRotate,
    RandZoom,
)

import SimpleITK as sitk
import nibabel as nib
from monai.data import set_track_meta

In [45]:
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.model_selection import GroupShuffleSplit
from sklearn.utils.class_weight import compute_class_weight
import os
from tensorflow.keras.layers import Input, Conv3D, MaxPooling3D, BatchNormalization, Activation, GlobalAveragePooling3D, Dropout, Dense, concatenate
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import CategoricalCrossentropy

In [6]:
df = pd.read_csv('/content/labels.csv')

In [7]:
set_track_meta(False)

Loading Dataset Index

In [8]:
df.head()

        filename      label
0   10250_T2.npy      Mixed
1  10352_T11.npy  No Lesion
2  10352_T12.npy  No Lesion
3   10352_L1.npy  No Lesion
4   10352_L2.npy  No Lesion

Extracting Patient ID and Vertebrae Level from the filename

In [9]:
df['Patient_ID'] = df['filename'].apply(lambda x: x.split('_')[0])
df['Vertebra_Level'] = df['filename'].apply(lambda x: x.split('_')[1].replace('.npy', ''))

Loading Data and Split By Patient

In [13]:
df['label']

0          Mixed
1      No Lesion
2      No Lesion
3      No Lesion
4      No Lesion
         ...
284        Lytic
285        Lytic
286        Lytic
287        Lytic
288        Lytic
Name: label, Length: 289, dtype: object

Label Mapping

In [14]:
#Label Mapping
label_mapping = {'No Lesion': 0, 'Lytic': 1, 'Blastic': 2, 'Mixed': 3}
df['label_int'] = df['label'].map(label_mapping)

In [16]:
TENSOR_DIR = "drive/MyDrive/TCIA_Original/tensors"

3D Augmentation

In [17]:
train_transforms = Compose([
    # 1. Left/Right Flip
    RandFlip(prob=0.5, spatial_axis=2),

    # 2. Subtle Rotations
    RandRotate(range_x=0.17, range_y=0.17, range_z=0.17, prob=0.5),

    # 3. Subtle Zooming
    RandZoom(min_zoom=0.9, max_zoom=1.1, prob=0.5)
])

Helper Functions

In [46]:
def parse_npy_with_monai(filename, label, is_training):
    filepath = os.path.join(TENSOR_DIR, filename.decode('utf-8'))
    tensor = np.load(filepath).astype(np.float32)

    if is_training:
        tensor = np.expand_dims(tensor, axis=0)
        tensor = train_transforms(tensor)
        tensor = np.asarray(tensor)
        tensor = np.moveaxis(tensor, 0, -1)
    else:
        tensor = np.expand_dims(tensor, axis=-1)

    return tensor, label





def tf_load_train(filename, label):
    tensor, label = tf.numpy_function(
        func=lambda f, l: parse_npy_with_monai(f, l, is_training=True),
        inp=[filename, label], Tout=[tf.float32, tf.int32]
    )
    tensor.set_shape((64, 64, 64, 1))
    label.set_shape(())
    return tensor, label

def tf_load_val(filename, label):
    tensor, label = tf.numpy_function(
        func=lambda filename, label: parse_npy_with_monai(filename, label, is_training=False),
        inp=[filename, label],
        Tout=[tf.float32, tf.int32]
    )
    tensor.set_shape((64, 64, 64, 1))
    label.set_shape(())
    return tensor, tf.cast(label, tf.int32)

In [47]:
def create_dataset(dataframe, batch_size=8, is_training=False):
    ds = tf.data.Dataset.from_tensor_slices((dataframe['filename'].values, dataframe['label_int'].values))

    if is_training:
        ds = ds.shuffle(buffer_size=len(dataframe))
        ds = ds.map(tf_load_train, num_parallel_calls=tf.data.AUTOTUNE)
    else:
        ds = ds.map(tf_load_val, num_parallel_calls=tf.data.AUTOTUNE)

    return ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)

In [60]:
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# 1. Define strict Callbacks

training_callbacks = [
    EarlyStopping(
        monitor='val_loss',
        patience=20,
        restore_best_weights=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=8,
        min_lr=1e-6,
        verbose=1
    )
]

Model Definition

In [49]:
def inception_3d_block(x, f1x1, f3x3_reduce, f3x3, f5x5_reduce, f5x5, fpool):
    # Path 1: 1x1x1 Convolution (Extracts basic features)
    path1 = Conv3D(f1x1, (1, 1, 1), padding='same')(x)
    path1 = BatchNormalization()(path1)
    path1 = Activation('relu')(path1)

    # Path 2: 1x1x1 → 3x3x3 Convolution (Captures mid-range features)
    path2 = Conv3D(f3x3_reduce, (1, 1, 1), padding='same')(x)
    path2 = Activation('relu')(path2)

    path2 = Conv3D(f3x3, (3, 3, 3), padding='same')(path2)
    path2 = Activation('relu')(path2)

    # Path 3: 1x1x1 → 5x5x5 Convolution (Captures larger features)
    path3 = Conv3D(f5x5_reduce, (1, 1, 1), padding='same')(x)
    path3 = Activation('relu')(path3)

    path3 = Conv3D(f5x5, (5, 5, 5), padding='same')(path3)
    path3 = Activation('relu')(path3)

    # Path 4: 3x3x3 Max Pool → 1x1x1 Convolution (Captures background information)
    path4 = MaxPooling3D((3, 3, 3), strides=(1, 1, 1), padding='same')(x)
    path4 = Conv3D(fpool, (1, 1, 1), padding='same')(path4)
    path4 = Activation('relu')(path4)

    # Final Step: Concatenate all paths
    return concatenate([path1, path2, path3, path4], axis=-1)

Model Training

In [24]:
def SimpleI3DNet2(input_shape=(64, 64, 64, 1), num_classes=4):
    """"Added label smoothening and converted labels to one-hot encoded"""

    inputs = Input(shape=input_shape)

    # Initial 3D Convolution & Pooling
    x = Conv3D(64, (7, 7, 7), strides=(2, 2, 2), padding='same')(inputs)
    x = Activation('relu')(x)
    x = MaxPooling3D((3, 3, 3), strides=(2, 2, 2), padding='same')(x)

    # First I3D Inception Block
    x = inception_3d_block(x, 64, 96, 128, 16, 32, 32)

    # Second I3D Inception Block
    x = inception_3d_block(x, 128, 128, 192, 32, 96, 64)

    # Pooling layer
    x = MaxPooling3D((3, 3, 3), strides=(2, 2, 2), padding='same')(x)

    # Third I3D Inception Block
    x = inception_3d_block(x, 192, 96, 208, 16, 48, 64)

    # Global Average Pooling
    x = GlobalAveragePooling3D()(x)
    x = Dropout(0.5)(x)

    # Fully connected layer for classification
    x = Dense(num_classes, activation='softmax')(x)

    # Define the model
    model = Model(inputs=inputs, outputs=x)

    # UPDATED: Switched back to sparse_categorical_crossentropy to prevent one-hot VRAM crashes
    model.compile(optimizer=Adam(learning_rate=1e-3),
                  loss=CategoricalCrossentropy(label_smoothing=0.1),
                  metrics=['accuracy'],
                  )

    return model

In [25]:
K_FOLDS = 5
sgkf = StratifiedGroupKFold(n_splits=K_FOLDS, shuffle=True, random_state=42)
fold_metrics = []
oof_true_labels = []
oof_predictions = []

In [51]:
for fold, (train_idx, val_idx) in enumerate(sgkf.split(df, df['label_int'], df['Patient_ID'])):
    print(f"\n               FOLD {fold + 1}")
    print(f"{'='*40}")

    train_df = df.iloc[train_idx].copy()
    val_df = df.iloc[val_idx].copy()

    print(f"Training on {train_df['Patient_ID'].nunique()} patients ({len(train_df)} volumes)")
    print(f"Testing on {val_df['Patient_ID'].nunique()} patients ({len(val_df)} volumes)")

    weights = compute_class_weight('balanced', classes=np.unique(train_df['label_int']), y=train_df['label_int'])
    class_weights_dict = {i: weight for i, weight in enumerate(weights)}

    # Explicitly cast label_int to np.int32 to match tf.numpy_function's Tout declaration
    train_df['label_int'] = train_df['label_int'].astype(np.int32)
    val_df['label_int'] = val_df['label_int'].astype(np.int32)

    train_ds = create_dataset(train_df, batch_size=8, is_training=True)
    val_ds = create_dataset(val_df, batch_size=8, is_training=False)

    # Helper function to convert integer labels to one-hot for CategoricalCrossentropy
    def convert_to_one_hot_labels(image, label_int_scalar):
        num_classes = 4  # Assuming 4 classes as per SimpleI3DNet2
        return image, tf.one_hot(tf.cast(label_int_scalar, tf.int32), depth=num_classes)

    # Apply the conversion to the datasets
    train_ds = train_ds.map(convert_to_one_hot_labels, num_parallel_calls=tf.data.AUTOTUNE)
    val_ds = val_ds.map(convert_to_one_hot_labels, num_parallel_calls=tf.data.AUTOTUNE)

    # 3. Build a new model and prevent weight leaks
    tf.keras.backend.clear_session()

    model = SimpleI3DNet2()


    # 5. Model train
    history = model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=50,
        class_weight=class_weights_dict,
        callbacks=training_callbacks, # Injected Callbacks
        verbose=1
    )

    # 6. Final validation accuracy
    # IMPORTANT: Because EarlyStopping restores the BEST weights, looking at the last epoch of `history`
    # is inaccurate. We must run a quick evaluate() to get the true restored performance.
    val_loss, final_val_acc = model.evaluate(val_ds, verbose=0)
    fold_metrics.append(final_val_acc)
    print(f"Fold {fold + 1} Best Restored Validation Accuracy: {final_val_acc:.4f}")

    # 7. CAPTURE OUT-OF-FOLD (OOF) PREDICTIONS
    print(f"Gathering predictions for Fold {fold + 1} validation patients...")
    for images, labels in val_ds:
        # labels are currently one-hot arrays (e.g. [0, 0, 1, 0]).
        # Convert back to integers (e.g. 2) for the final Confusion Matrix and Classification Report
        true_classes = np.argmax(labels.numpy(), axis=-1)
        oof_true_labels.extend(true_classes)

        preds = model.predict(images, verbose=0)
        oof_predictions.extend(preds)

               FOLD 1
========================================
Training on 39 patients (243 volumes)
Testing on 13 patients (46 volumes)
Epoch 1/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 95s 2s/step - accuracy: 0.3621 - loss: 1.6036 - val_accuracy: 0.0652 - val_loss: 2.1702 - learning_rate: 0.0010
Epoch 2/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 198ms/step - accuracy: 0.4650 - loss: 1.3108 - val_accuracy: 0.1304 - val_loss: 1.7331 - learning_rate: 0.0010
Epoch 3/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 222ms/step - accuracy: 0.5103 - loss: 1.2445 - val_accuracy: 0.5000 - val_loss: 1.2910 - learning_rate: 0.0010
Epoch 4/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 199ms/step - accuracy: 0.5350 - loss: 1.1524 - val_accuracy: 0.1304 - val_loss: 1.4165 - learning_rate: 0.0010
Epoch 5/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 8s 247ms/step - accuracy: 0.5103 - loss: 1.1684 - val_accuracy: 0.1304 - val_loss: 1.6018 - learning_rate: 0.0010
Epoch 6/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 188ms/step - accuracy: 0.5391 - loss: 1.1309 - val_accuracy: 0.1522 - val_loss: 1.4401 - learning_rate: 0.0010
Epoch 7/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 229ms/step - accuracy: 0.5720 - loss: 1.0957 - val_accuracy: 0.2609 - val_loss: 1.3572 - learning_rate: 0.0010
Epoch 8/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - accuracy: 0.5852 - loss: 1.0259
Epoch 8: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 182ms/step - accuracy: 0.5556 - loss: 1.0632 - val_accuracy: 0.5217 - val_loss: 1.3861 - learning_rate: 0.0010
Epoch 9/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 213ms/step - accuracy: 0.5761 - loss: 1.0663 - val_accuracy: 0.5217 - val_loss: 1.9296 - learning_rate: 5.0000e-04
Epoch 10/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 9s 182ms/step - accuracy: 0.6379 - loss: 1.0351 - val_accuracy: 0.5652 - val_loss: 1.5956 - learning_rate: 5.0000e-04
Epoch 11/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 226ms/step - accuracy: 0.5802 - loss: 1.0462 - val_accuracy: 0.4130 - val_loss: 1.3714 - learning_rate: 5.0000e-04
Epoch 12/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 188ms/step - accuracy: 0.6255 - loss: 1.0114 - val_accuracy: 0.5435 - val_loss: 1.7166 - learning_rate: 5.0000e-04
Epoch 13/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 208ms/step - accuracy: 0.5908 - loss: 1.0504
Epoch 13: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 223ms/step - accuracy: 0.5967 - loss: 1.0099 - val_accuracy: 0.2826 - val_loss: 1.3810 - learning_rate: 5.0000e-04
Epoch 13: early stopping
Restoring model weights from the end of the best epoch: 3.
Fold 1 Best Restored Validation Accuracy: 0.5000
Gathering predictions for Fold 1 validation patients...

               FOLD 2
========================================
Training on 42 patients (203 volumes)
Testing on 10 patients (86 volumes)
Epoch 1/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 37s 769ms/step - accuracy: 0.3350 - loss: 1.7314 - val_accuracy: 0.2209 - val_loss: 1.5331 - learning_rate: 0.0010
Epoch 2/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 207ms/step - accuracy: 0.3842 - loss: 1.3015 - val_accuracy: 0.5233 - val_loss: 1.1929 - learning_rate: 0.0010
Epoch 3/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 213ms/step - accuracy: 0.3793 - loss: 1.3438 - val_accuracy: 0.2209 - val_loss: 1.4270 - learning_rate: 0.0010
Epoch 4/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 225ms/step - accuracy: 0.3695 - loss: 1.3432 - val_accuracy: 0.4186 - val_loss: 1.4580 - learning_rate: 0.0010
Epoch 5/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 217ms/step - accuracy: 0.4138 - loss: 1.2718 - val_accuracy: 0.1860 - val_loss: 1.2537 - learning_rate: 0.0010
Epoch 6/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - accuracy: 0.4286 - loss: 1.2567 - val_accuracy: 0.2907 - val_loss: 1.4051 - learning_rate: 0.0010
Epoch 7/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - accuracy: 0.4627 - loss: 1.2087
Epoch 7: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 207ms/step - accuracy: 0.4532 - loss: 1.2534 - val_accuracy: 0.0465 - val_loss: 1.8471 - learning_rate: 0.0010
Epoch 8/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 236ms/step - accuracy: 0.4384 - loss: 1.2046 - val_accuracy: 0.1395 - val_loss: 1.6085 - learning_rate: 5.0000e-04
Epoch 9/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 199ms/step - accuracy: 0.4680 - loss: 1.2075 - val_accuracy: 0.2558 - val_loss: 1.3504 - learning_rate: 5.0000e-04
Epoch 10/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 7s 249ms/step - accuracy: 0.4729 - loss: 1.1396 - val_accuracy: 0.4070 - val_loss: 1.5919 - learning_rate: 5.0000e-04
Epoch 11/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 198ms/step - accuracy: 0.5271 - loss: 1.1112 - val_accuracy: 0.2442 - val_loss: 1.4576 - learning_rate: 5.0000e-04
Epoch 12/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 203ms/step - accuracy: 0.5468 - loss: 1.1377 - val_accuracy: 0.4651 - val_loss: 1.0444 - learning_rate: 5.0000e-04
Epoch 13/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 219ms/step - accuracy: 0.5369 - loss: 1.1166 - val_accuracy: 0.4302 - val_loss: 1.1861 - learning_rate: 5.0000e-04
Epoch 14/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 202ms/step - accuracy: 0.5172 - loss: 1.1223 - val_accuracy: 0.3488 - val_loss: 2.0964 - learning_rate: 5.0000e-04
Epoch 15/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 7s 248ms/step - accuracy: 0.5517 - loss: 1.1162 - val_accuracy: 0.2558 - val_loss: 1.3145 - learning_rate: 5.0000e-04
Epoch 16/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 206ms/step - accuracy: 0.5567 - loss: 1.0874 - val_accuracy: 0.5233 - val_loss: 1.0696 - learning_rate: 5.0000e-04
Epoch 17/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 210ms/step - accuracy: 0.5123 - loss: 1.1304 - val_accuracy: 0.6977 - val_loss: 0.8897 - learning_rate: 5.0000e-04
Epoch 18/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 231ms/step - accuracy: 0.5764 - loss: 1.0856 - val_accuracy: 0.7558 - val_loss: 0.8500 - learning_rate: 5.0000e-04
Epoch 19/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 205ms/step - accuracy: 0.5419 - loss: 1.0622 - val_accuracy: 0.3837 - val_loss: 1.3476 - learning_rate: 5.0000e-04
Epoch 20/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 10s 200ms/step - accuracy: 0.6010 - loss: 1.0122 - val_accuracy: 0.2674 - val_loss: 1.9632 - learning_rate: 5.0000e-04
Epoch 21/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 205ms/step - accuracy: 0.6207 - loss: 1.0336 - val_accuracy: 0.6279 - val_loss: 0.9608 - learning_rate: 5.0000e-04
Epoch 22/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 218ms/step - accuracy: 0.5911 - loss: 1.0349 - val_accuracy: 0.4302 - val_loss: 2.8344 - learning_rate: 5.0000e-04
Epoch 23/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - accuracy: 0.6394 - loss: 1.0313
Epoch 23: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 203ms/step - accuracy: 0.5911 - loss: 1.0451 - val_accuracy: 0.7326 - val_loss: 0.8782 - learning_rate: 5.0000e-04
Epoch 24/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 7s 247ms/step - accuracy: 0.6453 - loss: 1.0087 - val_accuracy: 0.7791 - val_loss: 0.8077 - learning_rate: 2.5000e-04
Epoch 25/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 204ms/step - accuracy: 0.6158 - loss: 0.9973 - val_accuracy: 0.7674 - val_loss: 0.8719 - learning_rate: 2.5000e-04
Epoch 26/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 206ms/step - accuracy: 0.6010 - loss: 0.9751 - val_accuracy: 0.5814 - val_loss: 0.9502 - learning_rate: 2.5000e-04
Epoch 27/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 222ms/step - accuracy: 0.6404 - loss: 0.9952 - val_accuracy: 0.6163 - val_loss: 1.0021 - learning_rate: 2.5000e-04
Epoch 28/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 202ms/step - accuracy: 0.6010 - loss: 0.9839 - val_accuracy: 0.7326 - val_loss: 0.8325 - learning_rate: 2.5000e-04
Epoch 29/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step - accuracy: 0.6852 - loss: 0.9531
Epoch 29: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
26/26 ━━━━━━━━━━━━━━━━━━━━ 7s 247ms/step - accuracy: 0.6897 - loss: 0.9288 - val_accuracy: 0.7558 - val_loss: 0.8401 - learning_rate: 2.5000e-04
Epoch 30/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 202ms/step - accuracy: 0.6798 - loss: 0.9214 - val_accuracy: 0.6977 - val_loss: 0.8721 - learning_rate: 1.2500e-04
Epoch 31/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 204ms/step - accuracy: 0.6946 - loss: 0.8805 - val_accuracy: 0.6744 - val_loss: 0.8860 - learning_rate: 1.2500e-04
Epoch 32/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 225ms/step - accuracy: 0.7143 - loss: 0.8597 - val_accuracy: 0.5581 - val_loss: 1.0004 - learning_rate: 1.2500e-04
Epoch 33/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 202ms/step - accuracy: 0.6847 - loss: 0.9009 - val_accuracy: 0.5814 - val_loss: 0.9595 - learning_rate: 1.2500e-04
Epoch 34/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - accuracy: 0.7098 - loss: 0.9021
Epoch 34: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
26/26 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - accuracy: 0.7094 - loss: 0.8765 - val_accuracy: 0.6744 - val_loss: 0.9422 - learning_rate: 1.2500e-04
Epoch 34: early stopping
Restoring model weights from the end of the best epoch: 24.
Fold 2 Best Restored Validation Accuracy: 0.7791
Gathering predictions for Fold 2 validation patients...

               FOLD 3
========================================
Training on 42 patients (245 volumes)
Testing on 10 patients (44 volumes)
Epoch 1/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 45s 910ms/step - accuracy: 0.3878 - loss: 1.5313 - val_accuracy: 0.1364 - val_loss: 1.9242 - learning_rate: 0.0010
Epoch 2/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 197ms/step - accuracy: 0.4449 - loss: 1.2896 - val_accuracy: 0.0682 - val_loss: 1.6729 - learning_rate: 0.0010
Epoch 3/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 225ms/step - accuracy: 0.5796 - loss: 1.1569 - val_accuracy: 0.1136 - val_loss: 1.8970 - learning_rate: 0.0010
Epoch 4/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 199ms/step - accuracy: 0.4980 - loss: 1.2174 - val_accuracy: 0.7045 - val_loss: 1.0816 - learning_rate: 0.0010
Epoch 5/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step - accuracy: 0.5894 - loss: 1.2014
Epoch 5: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 224ms/step - accuracy: 0.5510 - loss: 1.1852 - val_accuracy: 0.7045 - val_loss: 1.2050 - learning_rate: 0.0010
Epoch 6/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 189ms/step - accuracy: 0.5673 - loss: 1.1229 - val_accuracy: 0.3636 - val_loss: 1.2188 - learning_rate: 5.0000e-04
Epoch 7/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 236ms/step - accuracy: 0.5918 - loss: 1.1013 - val_accuracy: 0.1136 - val_loss: 1.5096 - learning_rate: 5.0000e-04
Epoch 8/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 185ms/step - accuracy: 0.5592 - loss: 1.0979 - val_accuracy: 0.2273 - val_loss: 1.4858 - learning_rate: 5.0000e-04
Epoch 9/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 197ms/step - accuracy: 0.6531 - loss: 1.0098 - val_accuracy: 0.7045 - val_loss: 1.1654 - learning_rate: 5.0000e-04
Epoch 10/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - accuracy: 0.6088 - loss: 1.0167
Epoch 10: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
31/31 ━━━━━━━━━━━━━━━━━━━━ 10s 181ms/step - accuracy: 0.5959 - loss: 1.0513 - val_accuracy: 0.1591 - val_loss: 1.5343 - learning_rate: 5.0000e-04
Epoch 10: early stopping
Restoring model weights from the end of the best epoch: 1.
Fold 3 Best Restored Validation Accuracy: 0.1364
Gathering predictions for Fold 3 validation patients...

               FOLD 4
========================================
Training on 43 patients (226 volumes)
Testing on 9 patients (63 volumes)
Epoch 1/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 44s 931ms/step - accuracy: 0.3628 - loss: 1.5980 - val_accuracy: 0.3333 - val_loss: 1.6493 - learning_rate: 0.0010
Epoch 2/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 201ms/step - accuracy: 0.4646 - loss: 1.2563 - val_accuracy: 0.3651 - val_loss: 1.6023 - learning_rate: 0.0010
Epoch 3/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 222ms/step - accuracy: 0.4735 - loss: 1.2356 - val_accuracy: 0.3333 - val_loss: 1.4410 - learning_rate: 0.0010
Epoch 4/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 206ms/step - accuracy: 0.4690 - loss: 1.2401 - val_accuracy: 0.0317 - val_loss: 1.5979 - learning_rate: 0.0010
Epoch 5/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step - accuracy: 0.4875 - loss: 1.1810
Epoch 5: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 238ms/step - accuracy: 0.5088 - loss: 1.1442 - val_accuracy: 0.0952 - val_loss: 1.7280 - learning_rate: 0.0010
Epoch 6/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 9s 196ms/step - accuracy: 0.5531 - loss: 1.1561 - val_accuracy: 0.1111 - val_loss: 1.5022 - learning_rate: 5.0000e-04
Epoch 7/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 220ms/step - accuracy: 0.5531 - loss: 1.1330 - val_accuracy: 0.1270 - val_loss: 1.5237 - learning_rate: 5.0000e-04
Epoch 8/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 190ms/step - accuracy: 0.5619 - loss: 1.1325 - val_accuracy: 0.4444 - val_loss: 1.3106 - learning_rate: 5.0000e-04
Epoch 9/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 231ms/step - accuracy: 0.5442 - loss: 1.1185 - val_accuracy: 0.4921 - val_loss: 1.3492 - learning_rate: 5.0000e-04
Epoch 10/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - accuracy: 0.6450 - loss: 1.0094
Epoch 10: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 189ms/step - accuracy: 0.6549 - loss: 1.0155 - val_accuracy: 0.1111 - val_loss: 1.4892 - learning_rate: 5.0000e-04
Epoch 10: early stopping
Restoring model weights from the end of the best epoch: 1.
Fold 4 Best Restored Validation Accuracy: 0.3333
Gathering predictions for Fold 4 validation patients...

WARNING:tensorflow:5 out of the last 18 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x787f00ef2d40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

               FOLD 5
========================================
Training on 42 patients (239 volumes)
Testing on 10 patients (50 volumes)
Epoch 1/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 46s 956ms/step - accuracy: 0.3556 - loss: 1.6638 - val_accuracy: 0.2200 - val_loss: 1.5228 - learning_rate: 0.0010
Epoch 2/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 6s 198ms/step - accuracy: 0.4100 - loss: 1.3693 - val_accuracy: 0.4200 - val_loss: 1.3729 - learning_rate: 0.0010
Epoch 3/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 7s 220ms/step - accuracy: 0.4351 - loss: 1.2129 - val_accuracy: 0.4200 - val_loss: 1.4273 - learning_rate: 0.0010
Epoch 4/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - accuracy: 0.4644 - loss: 1.2060 - val_accuracy: 0.7200 - val_loss: 1.1574 - learning_rate: 0.0010
Epoch 5/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step - accuracy: 0.5907 - loss: 1.0270
Epoch 5: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
30/30 ━━━━━━━━━━━━━━━━━━━━ 6s 205ms/step - accuracy: 0.5356 - loss: 1.1799 - val_accuracy: 0.5400 - val_loss: 1.2526 - learning_rate: 0.0010
Epoch 6/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 6s 199ms/step - accuracy: 0.5188 - loss: 1.1744 - val_accuracy: 0.4600 - val_loss: 1.2393 - learning_rate: 5.0000e-04
Epoch 7/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 10s 189ms/step - accuracy: 0.5481 - loss: 1.1349 - val_accuracy: 0.6000 - val_loss: 1.0977 - learning_rate: 5.0000e-04
Epoch 8/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 7s 221ms/step - accuracy: 0.5858 - loss: 1.1620 - val_accuracy: 0.4400 - val_loss: 1.1629 - learning_rate: 5.0000e-04
Epoch 9/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 6s 189ms/step - accuracy: 0.5523 - loss: 1.1318 - val_accuracy: 0.4800 - val_loss: 1.2492 - learning_rate: 5.0000e-04
Epoch 10/50
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - accuracy: 0.5248 - loss: 1.1182
Epoch 10: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
30/30 ━━━━━━━━━━━━━━━━━━━━ 6s 192ms/step - accuracy: 0.5439 - loss: 1.1118 - val_accuracy: 0.5200 - val_loss: 1.1663 - learning_rate: 5.0000e-04
Epoch 10: early stopping
Restoring model weights from the end of the best epoch: 1.
Fold 5 Best Restored Validation Accuracy: 0.2200
Gathering predictions for Fold 5 validation patients...

WARNING:tensorflow:5 out of the last 15 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x787effd189a0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

In [52]:
fold_metrics

[0.5,
 0.7790697813034058,
 0.13636364042758942,
 0.3333333432674408,
 0.2199999988079071]

In [55]:
sum(fold_metrics)/5

0.3937533527612686

Instable validation accuracy

In [63]:
def SimpleI3DNet3(input_shape=(64, 64, 64, 1), num_classes=4):
    """"Added label smoothening and converted labels to one-hot encoded"""

    inputs = Input(shape=input_shape)

    # Initial 3D Convolution & Pooling
    x = Conv3D(64, (7, 7, 7), strides=(2, 2, 2), padding='same')(inputs)
    x = Activation('relu')(x)
    x = MaxPooling3D((3, 3, 3), strides=(2, 2, 2), padding='same')(x)

    # First I3D Inception Block
    x = inception_3d_block(x, 64, 96, 128, 16, 32, 32)

    # Second I3D Inception Block
    x = inception_3d_block(x, 128, 128, 192, 32, 96, 64)

    # Pooling layer
    x = MaxPooling3D((3, 3, 3), strides=(2, 2, 2), padding='same')(x)

    # Third I3D Inception Block
    x = inception_3d_block(x, 192, 96, 208, 16, 48, 64)

    # Global Average Pooling
    x = GlobalAveragePooling3D()(x)
    x = Dropout(0.5)(x)

    # Fully connected layer for classification
    x = Dense(num_classes, activation='softmax')(x)

    # Define the model
    model = Model(inputs=inputs, outputs=x)

    # UPDATED: Switched back to sparse_categorical_crossentropy to prevent one-hot VRAM crashes
    model.compile(optimizer=Adam(learning_rate=1e-4),
                  loss=CategoricalCrossentropy(label_smoothing=0.1),
                  metrics=['accuracy'],
                  )

    return model

In [64]:
for fold, (train_idx, val_idx) in enumerate(sgkf.split(df, df['label_int'], df['Patient_ID'])):
    print(f"\n               FOLD {fold + 1}")
    print(f"{'='*40}")

    train_df = df.iloc[train_idx].copy()
    val_df = df.iloc[val_idx].copy()

    print(f"Training on {train_df['Patient_ID'].nunique()} patients ({len(train_df)} volumes)")
    print(f"Testing on {val_df['Patient_ID'].nunique()} patients ({len(val_df)} volumes)")

    weights = compute_class_weight('balanced', classes=np.unique(train_df['label_int']), y=train_df['label_int'])
    class_weights_dict = {i: weight for i, weight in enumerate(weights)}

    train_df['label_int'] = train_df['label_int'].astype(np.int32)
    val_df['label_int'] = val_df['label_int'].astype(np.int32)

    train_ds = create_dataset(train_df, batch_size=8, is_training=True)
    val_ds = create_dataset(val_df, batch_size=8, is_training=False)

    def convert_to_one_hot_labels(image, label_int_scalar):
        num_classes = 4  # Assuming 4 classes as per SimpleI3DNet2
        return image, tf.one_hot(tf.cast(label_int_scalar, tf.int32), depth=num_classes)

    train_ds = train_ds.map(convert_to_one_hot_labels, num_parallel_calls=tf.data.AUTOTUNE)
    val_ds = val_ds.map(convert_to_one_hot_labels, num_parallel_calls=tf.data.AUTOTUNE)

    tf.keras.backend.clear_session()

    model = SimpleI3DNet3()
    history = model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=50,
        class_weight=class_weights_dict,
        callbacks=training_callbacks,
        verbose=1
    )


    val_loss, final_val_acc = model.evaluate(val_ds, verbose=0)
    fold_metrics.append(final_val_acc)
    print(f"Fold {fold + 1} Best Restored Validation Accuracy: {final_val_acc:.4f}")

    print(f"Gathering predictions for Fold {fold + 1} validation patients...")
    for images, labels in val_ds:
        true_classes = np.argmax(labels.numpy(), axis=-1)
        oof_true_labels.extend(true_classes)

        preds = model.predict(images, verbose=0)
        oof_predictions.extend(preds)

               FOLD 1
========================================
Training on 39 patients (243 volumes)
Testing on 13 patients (46 volumes)
Epoch 1/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 43s 839ms/step - accuracy: 0.3663 - loss: 1.4324 - val_accuracy: 0.1304 - val_loss: 1.4186 - learning_rate: 1.0000e-04
Epoch 2/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 211ms/step - accuracy: 0.4280 - loss: 1.2736 - val_accuracy: 0.1304 - val_loss: 1.4072 - learning_rate: 1.0000e-04
Epoch 3/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 9s 171ms/step - accuracy: 0.4033 - loss: 1.2901 - val_accuracy: 0.1304 - val_loss: 1.3574 - learning_rate: 1.0000e-04
Epoch 4/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 200ms/step - accuracy: 0.5391 - loss: 1.2480 - val_accuracy: 0.1304 - val_loss: 1.3595 - learning_rate: 1.0000e-04
Epoch 5/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 175ms/step - accuracy: 0.5350 - loss: 1.1655 - val_accuracy: 0.1522 - val_loss: 1.3850 - learning_rate: 1.0000e-04
Epoch 6/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 176ms/step - accuracy: 0.5267 - loss: 1.1853 - val_accuracy: 0.1304 - val_loss: 1.4015 - learning_rate: 1.0000e-04
Epoch 7/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 213ms/step - accuracy: 0.5761 - loss: 1.1099 - val_accuracy: 0.1522 - val_loss: 1.4301 - learning_rate: 1.0000e-04
Epoch 8/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 175ms/step - accuracy: 0.5514 - loss: 1.1492 - val_accuracy: 0.1522 - val_loss: 1.3712 - learning_rate: 1.0000e-04
Epoch 9/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 213ms/step - accuracy: 0.5350 - loss: 1.1138 - val_accuracy: 0.1304 - val_loss: 1.4154 - learning_rate: 1.0000e-04
Epoch 10/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 177ms/step - accuracy: 0.5967 - loss: 1.0764 - val_accuracy: 0.1304 - val_loss: 1.3373 - learning_rate: 1.0000e-04
Epoch 11/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 178ms/step - accuracy: 0.5761 - loss: 1.0811 - val_accuracy: 0.1304 - val_loss: 1.4422 - learning_rate: 1.0000e-04
Epoch 12/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 206ms/step - accuracy: 0.6049 - loss: 1.1009 - val_accuracy: 0.1522 - val_loss: 1.4121 - learning_rate: 1.0000e-04
Epoch 13/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 179ms/step - accuracy: 0.6667 - loss: 1.0126 - val_accuracy: 0.2174 - val_loss: 1.4183 - learning_rate: 1.0000e-04
Epoch 14/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 226ms/step - accuracy: 0.6173 - loss: 1.0134 - val_accuracy: 0.3261 - val_loss: 1.3881 - learning_rate: 1.0000e-04
Epoch 15/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 9s 179ms/step - accuracy: 0.6296 - loss: 0.9794 - val_accuracy: 0.2609 - val_loss: 1.4074 - learning_rate: 1.0000e-04
Epoch 16/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 219ms/step - accuracy: 0.6091 - loss: 0.9817 - val_accuracy: 0.4348 - val_loss: 1.3541 - learning_rate: 1.0000e-04
Epoch 17/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 181ms/step - accuracy: 0.6379 - loss: 1.0213 - val_accuracy: 0.3261 - val_loss: 1.4241 - learning_rate: 1.0000e-04
Epoch 18/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 214ms/step - accuracy: 0.6640 - loss: 0.9568
Epoch 18: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 229ms/step - accuracy: 0.6667 - loss: 0.9527 - val_accuracy: 0.3696 - val_loss: 1.4708 - learning_rate: 1.0000e-04
Epoch 19/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 182ms/step - accuracy: 0.6296 - loss: 0.9735 - val_accuracy: 0.3478 - val_loss: 1.4404 - learning_rate: 5.0000e-05
Epoch 20/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 191ms/step - accuracy: 0.7037 - loss: 0.9414 - val_accuracy: 0.3696 - val_loss: 1.4457 - learning_rate: 5.0000e-05
Epoch 21/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 189ms/step - accuracy: 0.6831 - loss: 0.8811 - val_accuracy: 0.4130 - val_loss: 1.4455 - learning_rate: 5.0000e-05
Epoch 22/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 191ms/step - accuracy: 0.7407 - loss: 0.8936 - val_accuracy: 0.3478 - val_loss: 1.5026 - learning_rate: 5.0000e-05
Epoch 23/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 211ms/step - accuracy: 0.7037 - loss: 0.9106 - val_accuracy: 0.3696 - val_loss: 1.4370 - learning_rate: 5.0000e-05
Epoch 24/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 186ms/step - accuracy: 0.6872 - loss: 0.8887 - val_accuracy: 0.4348 - val_loss: 1.3873 - learning_rate: 5.0000e-05
Epoch 25/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 225ms/step - accuracy: 0.6831 - loss: 0.9250 - val_accuracy: 0.3696 - val_loss: 1.4836 - learning_rate: 5.0000e-05
Epoch 26/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - accuracy: 0.7593 - loss: 0.8233
Epoch 26: ReduceLROnPlateau reducing learning rate to 2.499999936844688e-05.
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 185ms/step - accuracy: 0.7366 - loss: 0.8936 - val_accuracy: 0.1957 - val_loss: 1.6215 - learning_rate: 5.0000e-05
Epoch 27/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 197ms/step - accuracy: 0.7202 - loss: 0.8596 - val_accuracy: 0.3043 - val_loss: 1.5839 - learning_rate: 2.5000e-05
Epoch 28/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 190ms/step - accuracy: 0.7407 - loss: 0.8702 - val_accuracy: 0.3913 - val_loss: 1.4177 - learning_rate: 2.5000e-05
Epoch 29/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 189ms/step - accuracy: 0.7490 - loss: 0.8684 - val_accuracy: 0.3913 - val_loss: 1.4232 - learning_rate: 2.5000e-05
Epoch 30/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 215ms/step - accuracy: 0.7284 - loss: 0.8622 - val_accuracy: 0.3696 - val_loss: 1.4672 - learning_rate: 2.5000e-05
Epoch 30: early stopping
Restoring model weights from the end of the best epoch: 10.
Fold 1 Best Restored Validation Accuracy: 0.1304
Gathering predictions for Fold 1 validation patients...

               FOLD 2
========================================
Training on 42 patients (203 volumes)
Testing on 10 patients (86 volumes)
Epoch 1/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 39s 777ms/step - accuracy: 0.2759 - loss: 1.6652 - val_accuracy: 0.2209 - val_loss: 1.3556 - learning_rate: 1.0000e-04
Epoch 2/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 196ms/step - accuracy: 0.3695 - loss: 1.4075 - val_accuracy: 0.2209 - val_loss: 1.3397 - learning_rate: 1.0000e-04
Epoch 3/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 223ms/step - accuracy: 0.3695 - loss: 1.3574 - val_accuracy: 0.2907 - val_loss: 1.3399 - learning_rate: 1.0000e-04
Epoch 4/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 195ms/step - accuracy: 0.3892 - loss: 1.2736 - val_accuracy: 0.3140 - val_loss: 1.3630 - learning_rate: 1.0000e-04
Epoch 5/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 7s 257ms/step - accuracy: 0.4236 - loss: 1.3171 - val_accuracy: 0.3140 - val_loss: 1.3578 - learning_rate: 1.0000e-04
Epoch 6/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 197ms/step - accuracy: 0.3744 - loss: 1.2827 - val_accuracy: 0.3140 - val_loss: 1.3712 - learning_rate: 1.0000e-04
Epoch 7/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 201ms/step - accuracy: 0.4433 - loss: 1.2435 - val_accuracy: 0.3256 - val_loss: 1.3762 - learning_rate: 1.0000e-04
Epoch 8/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step - accuracy: 0.3913 - loss: 1.3484
Epoch 8: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 232ms/step - accuracy: 0.4138 - loss: 1.2690 - val_accuracy: 0.2093 - val_loss: 1.3556 - learning_rate: 1.0000e-04
Epoch 9/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 201ms/step - accuracy: 0.4581 - loss: 1.2645 - val_accuracy: 0.2093 - val_loss: 1.3484 - learning_rate: 5.0000e-05
Epoch 10/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 232ms/step - accuracy: 0.4778 - loss: 1.1713 - val_accuracy: 0.5233 - val_loss: 1.2693 - learning_rate: 5.0000e-05
Epoch 11/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - accuracy: 0.5222 - loss: 1.1943 - val_accuracy: 0.4302 - val_loss: 1.3000 - learning_rate: 5.0000e-05
Epoch 12/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 7s 261ms/step - accuracy: 0.5369 - loss: 1.1559 - val_accuracy: 0.5000 - val_loss: 1.2552 - learning_rate: 5.0000e-05
Epoch 13/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 9s 217ms/step - accuracy: 0.4384 - loss: 1.2173 - val_accuracy: 0.5233 - val_loss: 1.1904 - learning_rate: 5.0000e-05
Epoch 14/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 7s 252ms/step - accuracy: 0.4631 - loss: 1.1942 - val_accuracy: 0.5349 - val_loss: 1.0933 - learning_rate: 5.0000e-05
Epoch 15/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 224ms/step - accuracy: 0.4828 - loss: 1.2012 - val_accuracy: 0.5116 - val_loss: 1.1323 - learning_rate: 5.0000e-05
Epoch 16/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 7s 260ms/step - accuracy: 0.4778 - loss: 1.1858 - val_accuracy: 0.4884 - val_loss: 1.1034 - learning_rate: 5.0000e-05
Epoch 17/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 216ms/step - accuracy: 0.5567 - loss: 1.1140 - val_accuracy: 0.5349 - val_loss: 1.0052 - learning_rate: 5.0000e-05
Epoch 18/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 214ms/step - accuracy: 0.5172 - loss: 1.1787 - val_accuracy: 0.5465 - val_loss: 1.0920 - learning_rate: 5.0000e-05
Epoch 19/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 222ms/step - accuracy: 0.5468 - loss: 1.1089 - val_accuracy: 0.5465 - val_loss: 0.9987 - learning_rate: 5.0000e-05
Epoch 20/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 206ms/step - accuracy: 0.5025 - loss: 1.1329 - val_accuracy: 0.4884 - val_loss: 1.1163 - learning_rate: 5.0000e-05
Epoch 21/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 7s 252ms/step - accuracy: 0.5616 - loss: 1.1077 - val_accuracy: 0.5814 - val_loss: 0.9828 - learning_rate: 5.0000e-05
Epoch 22/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 5s 203ms/step - accuracy: 0.4729 - loss: 1.1279 - val_accuracy: 0.5465 - val_loss: 1.1225 - learning_rate: 5.0000e-05
Epoch 23/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 211ms/step - accuracy: 0.5369 - loss: 1.1314 - val_accuracy: 0.5233 - val_loss: 0.9793 - learning_rate: 5.0000e-05
Epoch 24/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 210ms/step - accuracy: 0.6355 - loss: 1.0402 - val_accuracy: 0.6744 - val_loss: 1.0372 - learning_rate: 5.0000e-05
Epoch 25/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 210ms/step - accuracy: 0.5074 - loss: 1.1284 - val_accuracy: 0.5698 - val_loss: 0.9780 - learning_rate: 5.0000e-05
Epoch 26/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 7s 249ms/step - accuracy: 0.5813 - loss: 1.1045 - val_accuracy: 0.6279 - val_loss: 0.9574 - learning_rate: 5.0000e-05
Epoch 27/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 211ms/step - accuracy: 0.5517 - loss: 1.0657 - val_accuracy: 0.5349 - val_loss: 1.0384 - learning_rate: 5.0000e-05
Epoch 28/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 218ms/step - accuracy: 0.6059 - loss: 1.0496 - val_accuracy: 0.6860 - val_loss: 0.9055 - learning_rate: 5.0000e-05
Epoch 29/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 213ms/step - accuracy: 0.5764 - loss: 1.0598 - val_accuracy: 0.6628 - val_loss: 0.9979 - learning_rate: 5.0000e-05
Epoch 30/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 216ms/step - accuracy: 0.6108 - loss: 1.0503 - val_accuracy: 0.5581 - val_loss: 1.0507 - learning_rate: 5.0000e-05
Epoch 31/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 7s 247ms/step - accuracy: 0.6256 - loss: 1.0652 - val_accuracy: 0.5814 - val_loss: 0.9791 - learning_rate: 5.0000e-05
Epoch 32/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 209ms/step - accuracy: 0.6010 - loss: 1.0136 - val_accuracy: 0.7442 - val_loss: 0.9172 - learning_rate: 5.0000e-05
Epoch 33/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 244ms/step - accuracy: 0.6059 - loss: 1.0818 - val_accuracy: 0.5930 - val_loss: 0.9783 - learning_rate: 5.0000e-05
Epoch 34/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 208ms/step - accuracy: 0.6010 - loss: 1.0285 - val_accuracy: 0.5930 - val_loss: 0.9555 - learning_rate: 5.0000e-05
Epoch 35/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 211ms/step - accuracy: 0.6502 - loss: 1.0183 - val_accuracy: 0.6512 - val_loss: 0.9634 - learning_rate: 5.0000e-05
Epoch 36/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step - accuracy: 0.5858 - loss: 1.0597
Epoch 36: ReduceLROnPlateau reducing learning rate to 2.499999936844688e-05.
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 225ms/step - accuracy: 0.5862 - loss: 1.0446 - val_accuracy: 0.6279 - val_loss: 0.9405 - learning_rate: 5.0000e-05
Epoch 37/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 208ms/step - accuracy: 0.6749 - loss: 0.9634 - val_accuracy: 0.6512 - val_loss: 0.9401 - learning_rate: 2.5000e-05
Epoch 38/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 236ms/step - accuracy: 0.6256 - loss: 1.0148 - val_accuracy: 0.5465 - val_loss: 0.9879 - learning_rate: 2.5000e-05
Epoch 39/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 210ms/step - accuracy: 0.6256 - loss: 0.9899 - val_accuracy: 0.5349 - val_loss: 0.9836 - learning_rate: 2.5000e-05
Epoch 40/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 215ms/step - accuracy: 0.6256 - loss: 1.0072 - val_accuracy: 0.6163 - val_loss: 0.9020 - learning_rate: 2.5000e-05
Epoch 41/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 235ms/step - accuracy: 0.6798 - loss: 0.9669 - val_accuracy: 0.5465 - val_loss: 1.0246 - learning_rate: 2.5000e-05
Epoch 42/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 213ms/step - accuracy: 0.6601 - loss: 0.9612 - val_accuracy: 0.5581 - val_loss: 1.0448 - learning_rate: 2.5000e-05
Epoch 43/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 238ms/step - accuracy: 0.6453 - loss: 0.9768 - val_accuracy: 0.5698 - val_loss: 0.9617 - learning_rate: 2.5000e-05
Epoch 44/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 211ms/step - accuracy: 0.6256 - loss: 0.9747 - val_accuracy: 0.5698 - val_loss: 0.9293 - learning_rate: 2.5000e-05
Epoch 45/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 215ms/step - accuracy: 0.6404 - loss: 0.9924 - val_accuracy: 0.6279 - val_loss: 0.8810 - learning_rate: 2.5000e-05
Epoch 46/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 223ms/step - accuracy: 0.5911 - loss: 0.9794 - val_accuracy: 0.7442 - val_loss: 0.9257 - learning_rate: 2.5000e-05
Epoch 47/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 6s 209ms/step - accuracy: 0.6355 - loss: 0.9999 - val_accuracy: 0.7093 - val_loss: 0.9156 - learning_rate: 2.5000e-05
Epoch 48/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 7s 265ms/step - accuracy: 0.6552 - loss: 0.9615 - val_accuracy: 0.5930 - val_loss: 0.9343 - learning_rate: 2.5000e-05
Epoch 49/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 9s 213ms/step - accuracy: 0.6355 - loss: 0.9785 - val_accuracy: 0.5930 - val_loss: 0.9220 - learning_rate: 2.5000e-05
Epoch 50/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 7s 241ms/step - accuracy: 0.6798 - loss: 0.9183 - val_accuracy: 0.5814 - val_loss: 0.9598 - learning_rate: 2.5000e-05
Restoring model weights from the end of the best epoch: 45.
Fold 2 Best Restored Validation Accuracy: 0.6279
Gathering predictions for Fold 2 validation patients...

               FOLD 3
========================================
Training on 42 patients (245 volumes)
Testing on 10 patients (44 volumes)
Epoch 1/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 39s 659ms/step - accuracy: 0.2980 - loss: 1.5337 - val_accuracy: 0.1364 - val_loss: 1.3644 - learning_rate: 1.0000e-04
Epoch 2/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 209ms/step - accuracy: 0.4122 - loss: 1.3007 - val_accuracy: 0.4773 - val_loss: 1.2886 - learning_rate: 1.0000e-04
Epoch 3/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 209ms/step - accuracy: 0.4776 - loss: 1.2726 - val_accuracy: 0.6818 - val_loss: 1.2319 - learning_rate: 1.0000e-04
Epoch 4/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 214ms/step - accuracy: 0.5224 - loss: 1.2007 - val_accuracy: 0.7045 - val_loss: 1.1883 - learning_rate: 1.0000e-04
Epoch 5/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 212ms/step - accuracy: 0.5306 - loss: 1.1656 - val_accuracy: 0.5000 - val_loss: 1.2577 - learning_rate: 1.0000e-04
Epoch 6/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 200ms/step - accuracy: 0.5102 - loss: 1.2033 - val_accuracy: 0.6818 - val_loss: 1.2077 - learning_rate: 1.0000e-04
Epoch 7/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 215ms/step - accuracy: 0.5265 - loss: 1.1829 - val_accuracy: 0.7045 - val_loss: 1.2070 - learning_rate: 1.0000e-04
Epoch 8/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step - accuracy: 0.5473 - loss: 1.1654
Epoch 8: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 191ms/step - accuracy: 0.5347 - loss: 1.1586 - val_accuracy: 0.6818 - val_loss: 1.1702 - learning_rate: 1.0000e-04
Epoch 9/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 8s 237ms/step - accuracy: 0.5959 - loss: 1.0751 - val_accuracy: 0.6818 - val_loss: 1.1901 - learning_rate: 5.0000e-05
Epoch 10/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 9s 189ms/step - accuracy: 0.6082 - loss: 1.1100 - val_accuracy: 0.6591 - val_loss: 1.2274 - learning_rate: 5.0000e-05
Epoch 11/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 217ms/step - accuracy: 0.6082 - loss: 1.0739 - val_accuracy: 0.6818 - val_loss: 1.1941 - learning_rate: 5.0000e-05
Epoch 12/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 193ms/step - accuracy: 0.6204 - loss: 1.0668 - val_accuracy: 0.2955 - val_loss: 1.3115 - learning_rate: 5.0000e-05
Epoch 13/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 8s 244ms/step - accuracy: 0.5959 - loss: 1.0489 - val_accuracy: 0.3636 - val_loss: 1.2860 - learning_rate: 5.0000e-05
Epoch 14/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - accuracy: 0.6449 - loss: 1.0547 - val_accuracy: 0.1364 - val_loss: 1.3702 - learning_rate: 5.0000e-05
Epoch 15/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 221ms/step - accuracy: 0.7061 - loss: 1.0196 - val_accuracy: 0.2500 - val_loss: 1.3667 - learning_rate: 5.0000e-05
Epoch 16/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step - accuracy: 0.6206 - loss: 0.9970
Epoch 16: ReduceLROnPlateau reducing learning rate to 2.499999936844688e-05.
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 201ms/step - accuracy: 0.6367 - loss: 1.0333 - val_accuracy: 0.0455 - val_loss: 1.5517 - learning_rate: 5.0000e-05
Epoch 17/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 7s 231ms/step - accuracy: 0.6612 - loss: 0.9823 - val_accuracy: 0.3182 - val_loss: 1.3260 - learning_rate: 2.5000e-05
Epoch 18/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 197ms/step - accuracy: 0.6531 - loss: 0.9680 - val_accuracy: 0.4773 - val_loss: 1.2332 - learning_rate: 2.5000e-05
Epoch 19/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 8s 240ms/step - accuracy: 0.6980 - loss: 0.9676 - val_accuracy: 0.5000 - val_loss: 1.2254 - learning_rate: 2.5000e-05
Epoch 20/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 6s 192ms/step - accuracy: 0.6816 - loss: 0.9788 - val_accuracy: 0.5227 - val_loss: 1.1970 - learning_rate: 2.5000e-05
Epoch 20: early stopping
Restoring model weights from the end of the best epoch: 1.
Fold 3 Best Restored Validation Accuracy: 0.1364
Gathering predictions for Fold 3 validation patients...

               FOLD 4
========================================
Training on 43 patients (226 volumes)
Testing on 9 patients (63 volumes)
Epoch 1/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 38s 694ms/step - accuracy: 0.3186 - loss: 1.4921 - val_accuracy: 0.2698 - val_loss: 1.3764 - learning_rate: 1.0000e-04
Epoch 2/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 214ms/step - accuracy: 0.4292 - loss: 1.3059 - val_accuracy: 0.2698 - val_loss: 1.4034 - learning_rate: 1.0000e-04
Epoch 3/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 200ms/step - accuracy: 0.4336 - loss: 1.2787 - val_accuracy: 0.2857 - val_loss: 1.4201 - learning_rate: 1.0000e-04
Epoch 4/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 239ms/step - accuracy: 0.4425 - loss: 1.2817 - val_accuracy: 0.2540 - val_loss: 1.4243 - learning_rate: 1.0000e-04
Epoch 5/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - accuracy: 0.4867 - loss: 1.1838 - val_accuracy: 0.3175 - val_loss: 1.4868 - learning_rate: 1.0000e-04
Epoch 6/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 213ms/step - accuracy: 0.4956 - loss: 1.1795 - val_accuracy: 0.3016 - val_loss: 1.4874 - learning_rate: 1.0000e-04
Epoch 7/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 195ms/step - accuracy: 0.5841 - loss: 1.1294 - val_accuracy: 0.3016 - val_loss: 1.4630 - learning_rate: 1.0000e-04
Epoch 8/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step - accuracy: 0.5033 - loss: 1.1171
Epoch 8: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 232ms/step - accuracy: 0.5000 - loss: 1.1797 - val_accuracy: 0.3016 - val_loss: 1.4911 - learning_rate: 1.0000e-04
Epoch 9/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 194ms/step - accuracy: 0.6283 - loss: 1.1180 - val_accuracy: 0.3016 - val_loss: 1.4975 - learning_rate: 5.0000e-05
Epoch 10/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 195ms/step - accuracy: 0.5531 - loss: 1.0979 - val_accuracy: 0.3016 - val_loss: 1.4932 - learning_rate: 5.0000e-05
Epoch 11/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 211ms/step - accuracy: 0.5929 - loss: 1.1123 - val_accuracy: 0.3016 - val_loss: 1.4181 - learning_rate: 5.0000e-05
Epoch 12/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 6s 192ms/step - accuracy: 0.6018 - loss: 1.0681 - val_accuracy: 0.3175 - val_loss: 1.4062 - learning_rate: 5.0000e-05
Epoch 13/50
29/29 ━━━━━━━━━━━━━━━━━━━━ 7s 238ms/step - accuracy: 0.6504 - loss: 1.0569 - val_accuracy: 0.2540 - val_loss: 1.4577 - learning_rate: 5.0000e-05
Epoch 14/50

In [71]:
fold_metrics[-5:]

[0.1304347813129425,
 0.6279069781303406,
 0.13636364042758942,
 0.2698412835597992,
 0.3400000035762787]

In [73]:
sum(fold_metrics[-5:])/5

0.3009093374013901